import { closePool, queryOne } from '../config/db';
import { closeRedis } from '../config/redis';
import { closeQueue } from '../queue/queues';
import { runMigrations } from '../db/migrator';
import { scheduleCampaign } from '../services/scheduler.service';
import { createLogger, describeError } from '../utils/logger';
import type { UserRow } from '../types/domain';

const log = createLogger('scripts:load-test');

/**
 * Schedules a large campaign in one shot so you can watch concurrency, the
 * inter-send delay and the hourly cap behave under load:
 *
 *   npm run seed:load -- --count 1000 --delay 500 --hourly 50 --startIn 10
 */
function arg(name: string, fallback: number): number {
  const index = process.argv.indexOf(`--${name}`);
  if (index === -1) return fallback;
  const value = Number(process.argv[index + 1]);
  return Number.isFinite(value) ? value : fallback;
}

async function main(): Promise<void> {
  await runMigrations();

  const count = arg('count', 1_000);
  const delayMs = arg('delay', 500);
  const hourlyLimit = arg('hourly', 50);
  const startInSeconds = arg('startIn', 10);

  // Load tests run without a browser session, so they reuse (or create) a
  // synthetic local user rather than requiring a Google login.
  const user = await queryOne<UserRow>(
    `INSERT INTO users (google_id, email, name)
     VALUES ('load-test', 'load-test@reachinbox.local', 'Load Test')
     ON CONFLICT (google_id) DO UPDATE SET last_login_at = now()
     RETURNING *`,
  );
  if (!user) throw new Error('Could not create the load-test user');

  const recipients = Array.from({ length: count }, (_, index) => ({
    email: `lead-${Date.now()}-${index}@example.com`,
    name: `Lead ${index + 1}`,
  }));

  const started = Date.now();
  const result = await scheduleCampaign({
    userId: user.id,
    name: `Load test ${new Date().toISOString()}`,
    subject: 'ReachInbox load test',
    body: 'This message was generated by the load-test script.',
    startAt: new Date(Date.now() + startInSeconds * 1_000),
    delayBetweenEmailsMs: delayMs,
    hourlyLimit,
    recipients,
  });

  log.info('Scheduled load-test campaign', {
    campaignId: result.campaign.id,
    scheduled: result.scheduledCount,
    tookMs: Date.now() - started,
    firstSendAt: result.firstSendAt?.toISOString(),
    lastSendAt: result.lastSendAt?.toISOString(),
  });
}

main()
  .catch((err) => {
    log.error('Load test failed', { error: describeError(err) });
    process.exitCode = 1;
  })
  .finally(async () => {
    await closeQueue();
    await closeRedis();
    await closePool();
  });
